---
title: "Notes from Literature Review on AOB power"
author: "Tyler Bradley"
date: "4/20/2019"
output: pdf_document
bibliography: aob-sources.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

| Source | Sample Location | Method | AOB Concentration |  Primer |
| ------ | --------------- | ------ | ----------------- | ------- |
| [@Hoefel_2005] | WTP and DWDS Bulk Water | MPN and qPCR | 3.14e4 +/- 1.47e2 copies/ml| See notes |
| [@Wang_2014] | DWDS Bulk Water | qPCR AmoA | 




# [@Hoefel_2005] 

This study was located in Australia. They used MPN assay and qPCR to measure both total bacteria and AOB in the WTP and in the drinking water system. They did not inspect or sample biofilms in this study. 

This study will likely be helpful when looking at methods used to analyze AOB in samples

Primers used:

  * Universal 16S by PCR -  **27F-1492R** primer set used for first run followed by nested amplification with **357F-GC–518R**
  * AOB specific - 30 cycles using **CTO** primer set was used for the first round. The products of this first round of sampling were used as the template for the nested PCR, which were performed using the **357F-GC–518R** primer set. 
  * NOB specific - **EUB338f-NIT3** was used to detect *Nitrobacter* and **EUB338f-Ntspa0685M** was used to detect *Nitrospira*
  * qPCR - For universal assay, DNA was extracted from a known amount of PCR products previously amplified using the **27F-1492R** primer. For AOB assay, DNA was extracted from known quantities of PCR products amplified from Nitrosospira multiformis ATCC 25196, using the **amoA1F-amoA2R** primer set.
  

Results: 

  * They found that AOB had an average concentraion of 3.14e4 +/- 1.47e2 copies/ml and that made up ~5.6% of the bacterial community. 
  * Looking at the number of active microbes in the system they found the concentration on average to be 3.43e3 copies/ml
  
  
# [@Wang_2014]

This study was conducted in Pinellas County, Florida. The utility was experience significant nitrification events. They chose to employ a chlorine burn strategy. Samples were taken before, during, and after the chlorine burn to characterize the microbial community and physiochemicla characteristics in the bulk water. 

The study does not give a detailed breakdown of the AOB qPCR results with the exception of a box and whiskers plot that shows the AOB qPCR results for each sampling time range (pre-burn, during burn, after burn, 4 months after burn). 

From this plot, we can see that the median value is roughly 1e3 copies/ml